Algoritmo "ListaEx12"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Jailson
// Descrição   :Leia o valor do lado de um quadrado e calcule sua área e
// seu perímetro.
// Autor(a)    : Alice Ferreira
// Data atual  : 20/04/2026
Var
   // Seção de Declarações das variáveis
   lado, area, perimetro: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Área e Perímetro de um Quadrado.")
   escreval("")
   escreva("Digite o valor do lado  do quadrado : ")
   leia(lado)
   escreval("")
   area<- lado * lado
   perimetro<- lado * 4
   escreval("A área do Quadradoé: ",area)
    escreval("")
     escreval("O Perímetro do Quadrado é: ", perimetro)
Fimalgoritmo



//
peri´metro=4×lado


