Algoritmo "ListaEx13"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Jailson
// Descrição   :Leia três números e calcule a média aritmética.
// Autor(a)    : Alice Ferreira
// Data atual  : 20/04/2026
Var
   // Seção de Declarações das variáveis
   v1, v2, v3, media: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Média de Três Valores.")
   escreval("")
   escreva("Digite o primeiro valor: ")
   leia(v1)
   escreval("")
   escreva("Digite o segundo valor: ")
   leia(v2)
   escreval("")
   escreva("Digite o terceiro valor: ")
   leia(v3)
   media<- ((v1 + v2 + v3) / 3)
   escreval("")
   escreval("Sua média é: ",media)


Fimalgoritmo






