Algoritmo "ListaEx2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :  jailson
// Descrição   : Leia o valor do lado de um quadrado e calcule sua área.
// Autor(a)    : Alice Ferreira
// Data atual  : 19/04/2026
Var
   // Seção de Declarações das variáveis
   lado , area: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Área quadrado.")
   escreval("")
   escreva("Digite o valor do lado do quadrado: ")
   leia(lado)
   escreval("")
   area<- lado * lado
   escreval("A área do quadrado é: ",area)

Fimalgoritmo