Algoritmo "ListaEx14"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Jailson
// Descrição   : Leia um valor em metros e converta para centímetros.
// Autor(a)    : Alice Ferreira
// Data atual  : 20/04/2026
Var
   // Seção de Declarações das variáveis
   v1, resultado: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Conversão de Metros para Centímetros")
   escreval("")
   escreva("Digite valor em metros(M): ")
   leia(v1)
   escreval("")
   resultado<- v1 * 100
   escreval("")
   escreval("Médida em centímetros (CM): ",resultado)


Fimalgoritmo






