Algoritmo "ListaEx22"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   :  Jailson
// Descrição   :  Leia dois valores armazenados nas variáveis A e B. Troque os
// valores entre elas.
// Autor(a)    : Alice Ferreira
// Data atual  : 06/04/2026
Var
   // Seção de Declarações das variáveis
   a, b: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval(" Troca de Valores")
   escreval("")
   escreva("Digite o Valor A: ")
   leia(a)
   escreval("")
   escreva("Digite o Valor B: ")
   leia(b)
   escreval("")
   escreval("O valor de A é: ", b)
   escreval("")
   escreval("O valor de B é: ", a)
Fimalgoritmo