Algoritmo "ListaEx7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :  jailson
// Descrição   : Leia o valor do raio de um círculo e calcule sua área.
// Autor(a)    : Alice Ferreira
// Data atual  : 19/04/2026
Var
   // Seção de Declarações das variáveis
   raio , area: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval(" Área do Círculo.")
   escreval("")
   escreva("Digite o valor do raio do círculo: ")
   leia(raio)
   escreval("")
  area<- (raio^2) * 3.14

   escreval("A área do círculo é: ",area)
Fimalgoritmo