Algoritmo "ListaEx8"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :  jailson
// Descrição   : Leia o raio de um círculo e calcule o comprimento da
//circunferência.
// Autor(a)    : Alice Ferreira
// Data atual  : 19/04/2026
Var
   // Seção de Declarações das variáveis
   raio , comprimentoc: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Comprimento da circunferência do Círculo.")
   escreval("")
   escreva("Digite o valor do raio do círculo: ")
   leia(raio)
   escreval("")
 comprimentoc<- raio * 3.14 * 2

   escreval("O comprimento da circunferência do Círculo é: ",comprimentoc)
Fimalgoritmo