Algoritmo "AntecessorPT1"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Recebe um número inteiro, e mostra o Antecessor
// Autor(a)    : Alice Ferreira Galas
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis
numero1: real
resultado: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um número:")
leia(numero1)
resultado<- numero1 - 1
Escreval("O antecessor é:",resultado)

Fimalgoritmo