Algoritmo "VerdadeiroFalsoPT1"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Jailson
// Descrição   : qual o resultado da avaliação das seguintes expressões lógicas:
// Autor(a)    : Alice Ferreira
// Data atual  : 19/04/2026
Var
   // Seção de Declarações das variáveis
   A, B, C: logico


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   A <- verdadeiro
   B <- verdadeiro
   C <- falso

   escreval("A = ", A)
   escreval("B = ", B)
   escreval("C = ", C)
   escreval("")

   escreval("a) A ou C e nao B = ", A ou C e nao B)
   escreval("b) (A ou B) e (A e C) = ", (A ou B) e (A e C))

Fimalgoritmo