Algoritmo "L01I"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Jailson
// Descrição   : Ler dois inteiros (variáveis A e B) e imprimir o resultad
// do quadrado da diferença do primeiro valor pelo segundo.
// Autor(a)    : Alice Ferreira
// Data atual  : 20/04/2026
Var
   // Seção de Declarações das variáveis
   a, b, resultado: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval(" resultado do quadrado da diferença (A) e (B).")
   escreval("")
   escreva("Digite o primeiro valor (A): ")
   leia(a)
   escreval("")
   escreva("Digite o segundo valor (B) ")
   leia(b)
   escreval("")
   resultado<- (a - b)^2
   
   escreval("O quadrado da diferença entre (A) e (B) é: ",resultado)
Fimalgoritmo



