Algoritmo "L01L"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Jailson
// Descrição   : Elaborar um programa que efetue a leitura de três valores
// (A, B e C) e apresente como resultado final à soma dos quadrados dos três
//lidos
// Autor(a)    : Alice Ferreira
// Data atual  : 20/04/2026
Var
   // Seção de Declarações das variáveis
 a, b, c, soma: real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("A soma dos quadrados dos três valores.")
   escreval("")
   escreva("Digite o Primeiro valor : ")
   leia(a)
   escreval("")
   escreva("Digite o segundo valor: ")
   leia(b)
   escreval("")
    escreva("Digite o terceiro valor: ")
   leia(c)
   escreval("")
   soma<- (a^2) + (b^2) + (c^2)

   escreval("A soma dos quadrados dos três valores é: ",soma)
Fimalgoritmo



